autogen.sh.in: simplify checks for autoconf and pkg-config
No need to check the versions there. pkg-config 0.8 was
released in 2003. autoconf version checks will be made
by autoreconf based on our requirement in configure.ac,
and it will error out for us in that case.

So just check for presence of these tools and get rid
of a whole lot of code.

diff --git a/autogen.sh.in b/autogen.sh.in
--- a/autogen.sh.in
+++ b/autogen.sh.in
@@ -4,7 +4,6 @@ test -n "$srcdir" || srcdir=.
 olddir=`pwd`
 cd "$srcdir"
 
-DIE=0
 package=@PACKAGE@
 srcfile=@SRCFILE@
 
@@ -47,13 +46,25 @@ fi
 autogen_options $@
 
 printf "+ check for build tools"
-if test ! -z "$NOCHECK"; then echo ": skipped version checks"; else  echo; fi
-version_check "autoreconf" "autoreconf " \
-              "ftp://ftp.gnu.org/pub/gnu/autoconf/" 2 68 || DIE=1
-version_check "pkg-config" "" \
-              "http://www.freedesktop.org/software/pkgconfig" 0 8 0 || DIE=1
+if test -z "$NOCHECK"; then
+  echo
 
-die_check $DIE
+  printf "  checking for autoreconf ... "
+  echo
+  which "autoreconf" 2>/dev/null || {
+    echo "not found! Please install the autoconf package."
+    exit 1
+  }
+
+  printf "  checking for pkg-config ... "
+  echo
+  which "pkg-config" 2>/dev/null || {
+    echo "not found! Please install pkg-config."
+    exit 1
+  }
+else
+  echo ": skipped version checks"
+fi
 
 # if no arguments specified then this will be printed
 if test -z "$*" && test -z "$NOCONFIGURE"; then
